## Configuration

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Set seaborn style for better visuals
sns.set(style="whitegrid")
# Optional: inline plotting for Jupyter Notebooks
%matplotlib inline
import chardet

## Customers

In [5]:
path = '../data/raw/Customers.csv'
with open(path, "rb") as f:
    result = chardet.detect(f.read(10000))
    print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [11]:
customers = pd.read_csv(path,encoding="latin1")
print(customers.shape)
customers.head()

(15266, 10)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [12]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

In [15]:
len(customers.CustomerKey.unique())

15266

In [29]:
customer_counts = customers.groupby(by='Country').count().sort_values(by='CustomerKey',ascending=False)[['CustomerKey']]
customer_counts['percentage'] = round(100 * customer_counts.CustomerKey / customer_counts.CustomerKey.sum(),1)
customer_counts

                CustomerKey  percentage
Country
United States          6828        44.7
United Kingdom         1944        12.7
Canada                 1553        10.2
Germany                1473         9.6
Australia              1420         9.3
Netherlands             733         4.8
France                  670         4.4
Italy                   645         4.2

Homework #1 : calculate the cumulative percentage and plot it

## Sales understanding